### ISSUE TITLE
cli seed doesn't work without first startup

### ISSUE THREAD

**Issue by wangbus** [epochtalk/epochtalk#323] opened 2017-08-16 15:58 UTC
Roles aren't populated.

```
   { error: insert or update on table "roles_users" violates foreign key constraint "roles_users_role_id_fkey"
       at Connection.parseE (/home/epoch/epochtalk/node_modules/pg/lib/connection.js:567:11)
       at Connection.parseMessage (/home/epoch/epochtalk/node_modules/pg/lib/connection.js:391:17)
       at Socket.<anonymous> (/home/epoch/epochtalk/node_modules/pg/lib/connection.js:129:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at TCP.onread (net.js:547:20)
     name: 'error',
     length: 301,
     severity: 'ERROR',
     code: '23503',
     detail: 'Key (role_id)=(8ab5ef49-c2ce-4421-9524-bb45f289d42c) is not present in table "roles".',
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: 'public',
     table: 'roles_users',
     column: undefined,
     dataType: undefined,
     constraint: 'roles_users_role_id_fkey',
     file: 'ri_triggers.c',
     line: '3324',
     routine: 'ri_ReportViolation' },
  isOperational: true,
  length: 301,
  severity: 'ERROR',
  code: '23503',
  detail: 'Key (role_id)=(8ab5ef49-c2ce-4421-9524-bb45f289d42c) is not present in table "roles".',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'roles_users',
  column: undefined,
  dataType: undefined,
  constraint: 'roles_users_role_id_fkey',
  file: 'ri_triggers.c',
  line: '3324',
  routine: 'ri_ReportViolation' }
```

**Comment by wangbus** [comment] 2017-08-16 15:58
requires first run. not optimal.

**Comment by akinsey** [comment] 2017-10-10 23:34
duplicate of #358

**Closed by akinsey** 2017-10-10 23:34 UTC
